version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nest_postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_network

  backend:
    build: .
    container_name: nest_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    networks:
      - nest_network
    command: npm run start:prod

volumes:
  postgres_data:

networks:
  nest_network:
    driver: bridge
