import { User } from 'types';

export const MOCK_USERS: User[] = [
  {
    id: 1,
    username: 'John Doe',
    email: '8m5yR@example.com',
    password: '$2b$10$eN8Jf3tone4RGBp53/6RBucBwz6ahLhCCxNyWZOlewCrLA0FANyse',
    refreshToken: 'refreshToken',
  },
  {
    id: 2,
    username: 'Robert Doe',
    email: '8m5yR@example.com',
    password: '$2b$10$eN8Jf3tone4RGBp53/6RBucBwz6ahLhCCxNyWZOlewCrLA0FANyse',
    refreshToken: 'refreshToken',
  },
  {
    id: 3,
    username: 'John Doe',
    email: '8m5yR@example.com',
    password: '$2b$10$eN8Jf3tone4RGBp53/6RBucBwz6ahLhCCxNyWZOlewCrLA0FANyse',
    refreshToken: 'refreshToken',
  },
  {
    id: 4,
    username: 'Robert Doe',
    email: '8m5yR@example.com',
    password: '$2b$10$eN8Jf3tone4RGBp53/6RBucBwz6ahLhCCxNyWZOlewCrLA0FANyse',
    refreshToken: 'refreshToken',
  },
  {
    id: 5,
    username: 'John Doe',
    email: '8m5yR@example.com',
    password: '$2b$10$eN8Jf3tone4RGBp53/6RBucBwz6ahLhCCxNyWZOlewCrLA0FANyse',
    refreshToken: 'refreshToken',
  },
  {
    id: 6,
    username: 'Robert Doe',
    email: '8m5yR@example.com',
    password: '$2b$10$eN8Jf3tone4RGBp53/6RBucBwz6ahLhCCxNyWZOlewCrLA0FANyse',
    refreshToken: 'refreshToken',
  },
  {
    id: 7,
    username: 'John Doe',
    email: '8m5yR@example.com',
    password: '$2b$10$eN8Jf3tone4RGBp53/6RBucBwz6ahLhCCxNyWZOlewCrLA0FANyse',
    refreshToken: 'refreshToken',
  },
  {
    id: 8,
    username: 'Robert Doe',
    email: '8m5yR@example.com',
    password: '$2b$10$eN8Jf3tone4RGBp53/6RBucBwz6ahLhCCxNyWZOlewCrLA0FANyse',
    refreshToken: 'refreshToken',
  },
  {
    id: 9,
    username: 'John Doe',
    email: '8m5yR@example.com',
    password: '$2b$10$eN8Jf3tone4RGBp53/6RBucBwz6ahLhCCxNyWZOlewCrLA0FANyse',
    refreshToken: 'refreshToken',
  },
  {
    id: 10,
    username: 'Robert Doe',
    email: '8m5yR@example.com',
    password: '$2b$10$eN8Jf3tone4RGBp53/6RBucBwz6ahLhCCxNyWZOlewCrLA0FANyse',
    refreshToken: 'refreshToken',
  },
  {
    id: 11,
    username: 'John Doe',
    email: '8m5yR@example.com',
    password: '$2b$10$eN8Jf3tone4RGBp53/6RBucBwz6ahLhCCxNyWZOlewCrLA0FANyse',
    refreshToken: 'refreshToken',
  },
  {
    id: 12,
    username: 'Robert Doe',
    email: '8m5yR@example.com',
    password: '$2b$10$eN8Jf3tone4RGBp53/6RBucBwz6ahLhCCxNyWZOlewCrLA0FANyse',
    refreshToken: 'refreshToken',
  },
];
